apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: cloudflareddns
    namespace: utilities
spec:
    interval: 5m
    chart:
        spec:
            # renovate: registryUrl=https://charts.truechartsoci.org
            chart: cloudflareddns
            version: 12.0.6
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
      image:
        tag: latest@sha256:51e8638867e5821812cd1b4c6f3cbda7ed7dda813881516e416b9fd5d18a28e1
      credentials:
        s3v3:
          type: s3
          url: "${S3_MINIO_URL_V2}"
          bucket: "${S3_MINIO_BUCKET_PREFIX}-{{ .Chart.Name }}"
          accessKey: "${S3_MINIO_KEY_ID_V2}"
          secretKey: "${S3_MINIO_SECRET_KEY_V2}"
          encrKey: "${S3_MINIO_SECRET_KEY_V2}"
      cloudflareddns:
        api_token: ${CLOUDFLARE_TOKEN}
        host_zone_record:
        - domain: vpn.${DOMAIN_0}
          record: A
          zone: ${ZONE_0}
      persistence:
        config:
          volsync:
          - name: config
            type: restic
            cleanupTempPVC: true
            cleanupCachePVC: true
            credentials: s3v3
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 10 0 * * *