apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-utils-pv # Give it a descriptive name'
  namespace: utilities
spec:
  capacity:
    storage: 100Gi # This is a placeholder; it doesn't limit the actual size
  accessModes:
    - ReadWriteMany # Or ReadWriteOnce if only one pod needs to write
  persistentVolumeReclaimPolicy: Retain # Important: Prevents data loss on PV deletion
  nfs:
    server: ${CONFIG_TRUENAS_IP}
    path: ${MEDIA_NFS_PATH}
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-utils-pvc # A name for your PVC
  namespace: utilities
spec:
  accessModes:
    - ReadWriteMany # Must match the PV's access modes
  resources:
    requests:
      storage: 100Gi # This should match the PV's storage value
  volumeName: plex-utils-pv